version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: 'on-failure'
    ports:
      - '3307:3306'
    volumes:
      - trend-gaza-mysql-vol:/var/lib/mysql
    env_file:
      - .env
  redis:
    restart: 'on-failure'
    image: redis:latest
    volumes:
      - trend-gaza-redis-vol:/var/lib/redis
    ports:
      - "6379:6379"
      
volumes:
  trend-gaza-mysql-vol:
  trend-gaza-redis-vol:  