name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.SUBMODULE_TOKEN }}
        submodules: recursive

    - name: Git Submodule Update
      run: git submodule update --remote --recursive

    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        build-root-directory: ./trend_gaza

    - name: Run chmod to make gradlew executable
      run: chmod +x ./trend_gaza/gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: ./trend_gaza

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build test
        build-root-directory: ./trend_gaza

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: '**/test-results/**/*.xml'

    - name: If the test fails, register a check comment in the failed code line
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
        token: ${{ github.token }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
